# Use the latest Python base image
FROM python:latest

# Set the working directory inside the container
WORKDIR /code

# Copy the Python script to the container's /code directory
COPY script.py /code

# Command to run the Python script
CMD ["python", "script.py"]